// ISSLCreateIndex.hpp
#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <regex>
#include <filesystem>
#include <fstream>
#include <boost/iostreams/device/mapped_file.hpp>
#define FMT_HEADER_ONLY
#include "../include/fmt/format.h"
#include "../include/libpopcnt/libpopcnt.h"